/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CatalogosRouteImport } from './routes/catalogos'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutosIndexRouteImport } from './routes/produtos.index'
import { Route as CatalogosIndexRouteImport } from './routes/catalogos.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProdutosSlugRouteImport } from './routes/produtos.$slug'
import { Route as PaginasSlugRouteImport } from './routes/paginas.$slug'
import { Route as CatalogosSlugRouteImport } from './routes/catalogos.$slug'
import { Route as AdminSolicitacoesRouteImport } from './routes/admin.solicitacoes'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as AdminFooterRouteImport } from './routes/admin.footer'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as AdminCatalogosRouteImport } from './routes/admin.catalogos'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminAtendimentosRouteImport } from './routes/admin.atendimentos'
import { Route as AdminAnunciosRouteImport } from './routes/admin.anuncios'
import { Route as AdminContasIndexRouteImport } from './routes/admin.contas.index'
import { Route as ApiPublicInitAdminRouteImport } from './routes/api/public/init-admin'
import { Route as AdminContasIdRouteImport } from './routes/admin.contas.$id'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogosRoute = CatalogosRouteImport.update({
  id: '/catalogos',
  path: '/catalogos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosIndexRoute = ProdutosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProdutosRoute,
} as any)
const CatalogosIndexRoute = CatalogosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CatalogosRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProdutosSlugRoute = ProdutosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProdutosRoute,
} as any)
const PaginasSlugRoute = PaginasSlugRouteImport.update({
  id: '/paginas/$slug',
  path: '/paginas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogosSlugRoute = CatalogosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CatalogosRoute,
} as any)
const AdminSolicitacoesRoute = AdminSolicitacoesRouteImport.update({
  id: '/solicitacoes',
  path: '/solicitacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFooterRoute = AdminFooterRouteImport.update({
  id: '/footer',
  path: '/footer',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogosRoute = AdminCatalogosRouteImport.update({
  id: '/catalogos',
  path: '/catalogos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAtendimentosRoute = AdminAtendimentosRouteImport.update({
  id: '/atendimentos',
  path: '/atendimentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnunciosRoute = AdminAnunciosRouteImport.update({
  id: '/anuncios',
  path: '/anuncios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContasIndexRoute = AdminContasIndexRouteImport.update({
  id: '/contas/',
  path: '/contas/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicInitAdminRoute = ApiPublicInitAdminRouteImport.update({
  id: '/api/public/init-admin',
  path: '/api/public/init-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContasIdRoute = AdminContasIdRouteImport.update({
  id: '/contas/$id',
  path: '/contas/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/catalogos': typeof CatalogosRouteWithChildren
  '/contato': typeof ContatoRoute
  '/dashboard': typeof DashboardRoute
  '/minha-conta': typeof MinhaContaRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/admin/anuncios': typeof AdminAnunciosRoute
  '/admin/atendimentos': typeof AdminAtendimentosRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/catalogos': typeof AdminCatalogosRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/footer': typeof AdminFooterRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/solicitacoes': typeof AdminSolicitacoesRoute
  '/catalogos/$slug': typeof CatalogosSlugRoute
  '/paginas/$slug': typeof PaginasSlugRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/catalogos/': typeof CatalogosIndexRoute
  '/produtos/': typeof ProdutosIndexRoute
  '/admin/contas/$id': typeof AdminContasIdRoute
  '/api/public/init-admin': typeof ApiPublicInitAdminRoute
  '/admin/contas/': typeof AdminContasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/dashboard': typeof DashboardRoute
  '/minha-conta': typeof MinhaContaRoute
  '/sobre': typeof SobreRoute
  '/admin/anuncios': typeof AdminAnunciosRoute
  '/admin/atendimentos': typeof AdminAtendimentosRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/catalogos': typeof AdminCatalogosRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/footer': typeof AdminFooterRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/solicitacoes': typeof AdminSolicitacoesRoute
  '/catalogos/$slug': typeof CatalogosSlugRoute
  '/paginas/$slug': typeof PaginasSlugRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/admin': typeof AdminIndexRoute
  '/catalogos': typeof CatalogosIndexRoute
  '/produtos': typeof ProdutosIndexRoute
  '/admin/contas/$id': typeof AdminContasIdRoute
  '/api/public/init-admin': typeof ApiPublicInitAdminRoute
  '/admin/contas': typeof AdminContasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/catalogos': typeof CatalogosRouteWithChildren
  '/contato': typeof ContatoRoute
  '/dashboard': typeof DashboardRoute
  '/minha-conta': typeof MinhaContaRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/admin/anuncios': typeof AdminAnunciosRoute
  '/admin/atendimentos': typeof AdminAtendimentosRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/catalogos': typeof AdminCatalogosRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/footer': typeof AdminFooterRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/solicitacoes': typeof AdminSolicitacoesRoute
  '/catalogos/$slug': typeof CatalogosSlugRoute
  '/paginas/$slug': typeof PaginasSlugRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/catalogos/': typeof CatalogosIndexRoute
  '/produtos/': typeof ProdutosIndexRoute
  '/admin/contas/$id': typeof AdminContasIdRoute
  '/api/public/init-admin': typeof ApiPublicInitAdminRoute
  '/admin/contas/': typeof AdminContasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/catalogos'
    | '/contato'
    | '/dashboard'
    | '/minha-conta'
    | '/produtos'
    | '/sobre'
    | '/admin/anuncios'
    | '/admin/atendimentos'
    | '/admin/banners'
    | '/admin/catalogos'
    | '/admin/categorias'
    | '/admin/configuracoes'
    | '/admin/footer'
    | '/admin/produtos'
    | '/admin/solicitacoes'
    | '/catalogos/$slug'
    | '/paginas/$slug'
    | '/produtos/$slug'
    | '/admin/'
    | '/catalogos/'
    | '/produtos/'
    | '/admin/contas/$id'
    | '/api/public/init-admin'
    | '/admin/contas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contato'
    | '/dashboard'
    | '/minha-conta'
    | '/sobre'
    | '/admin/anuncios'
    | '/admin/atendimentos'
    | '/admin/banners'
    | '/admin/catalogos'
    | '/admin/categorias'
    | '/admin/configuracoes'
    | '/admin/footer'
    | '/admin/produtos'
    | '/admin/solicitacoes'
    | '/catalogos/$slug'
    | '/paginas/$slug'
    | '/produtos/$slug'
    | '/admin'
    | '/catalogos'
    | '/produtos'
    | '/admin/contas/$id'
    | '/api/public/init-admin'
    | '/admin/contas'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/catalogos'
    | '/contato'
    | '/dashboard'
    | '/minha-conta'
    | '/produtos'
    | '/sobre'
    | '/admin/anuncios'
    | '/admin/atendimentos'
    | '/admin/banners'
    | '/admin/catalogos'
    | '/admin/categorias'
    | '/admin/configuracoes'
    | '/admin/footer'
    | '/admin/produtos'
    | '/admin/solicitacoes'
    | '/catalogos/$slug'
    | '/paginas/$slug'
    | '/produtos/$slug'
    | '/admin/'
    | '/catalogos/'
    | '/produtos/'
    | '/admin/contas/$id'
    | '/api/public/init-admin'
    | '/admin/contas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CatalogosRoute: typeof CatalogosRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  DashboardRoute: typeof DashboardRoute
  MinhaContaRoute: typeof MinhaContaRoute
  ProdutosRoute: typeof ProdutosRouteWithChildren
  SobreRoute: typeof SobreRoute
  PaginasSlugRoute: typeof PaginasSlugRoute
  ApiPublicInitAdminRoute: typeof ApiPublicInitAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogos': {
      id: '/catalogos'
      path: '/catalogos'
      fullPath: '/catalogos'
      preLoaderRoute: typeof CatalogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/': {
      id: '/produtos/'
      path: '/'
      fullPath: '/produtos/'
      preLoaderRoute: typeof ProdutosIndexRouteImport
      parentRoute: typeof ProdutosRoute
    }
    '/catalogos/': {
      id: '/catalogos/'
      path: '/'
      fullPath: '/catalogos/'
      preLoaderRoute: typeof CatalogosIndexRouteImport
      parentRoute: typeof CatalogosRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/produtos/$slug': {
      id: '/produtos/$slug'
      path: '/$slug'
      fullPath: '/produtos/$slug'
      preLoaderRoute: typeof ProdutosSlugRouteImport
      parentRoute: typeof ProdutosRoute
    }
    '/paginas/$slug': {
      id: '/paginas/$slug'
      path: '/paginas/$slug'
      fullPath: '/paginas/$slug'
      preLoaderRoute: typeof PaginasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogos/$slug': {
      id: '/catalogos/$slug'
      path: '/$slug'
      fullPath: '/catalogos/$slug'
      preLoaderRoute: typeof CatalogosSlugRouteImport
      parentRoute: typeof CatalogosRoute
    }
    '/admin/solicitacoes': {
      id: '/admin/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/admin/solicitacoes'
      preLoaderRoute: typeof AdminSolicitacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/footer': {
      id: '/admin/footer'
      path: '/footer'
      fullPath: '/admin/footer'
      preLoaderRoute: typeof AdminFooterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalogos': {
      id: '/admin/catalogos'
      path: '/catalogos'
      fullPath: '/admin/catalogos'
      preLoaderRoute: typeof AdminCatalogosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/atendimentos': {
      id: '/admin/atendimentos'
      path: '/atendimentos'
      fullPath: '/admin/atendimentos'
      preLoaderRoute: typeof AdminAtendimentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/anuncios': {
      id: '/admin/anuncios'
      path: '/anuncios'
      fullPath: '/admin/anuncios'
      preLoaderRoute: typeof AdminAnunciosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contas/': {
      id: '/admin/contas/'
      path: '/contas'
      fullPath: '/admin/contas/'
      preLoaderRoute: typeof AdminContasIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/init-admin': {
      id: '/api/public/init-admin'
      path: '/api/public/init-admin'
      fullPath: '/api/public/init-admin'
      preLoaderRoute: typeof ApiPublicInitAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contas/$id': {
      id: '/admin/contas/$id'
      path: '/contas/$id'
      fullPath: '/admin/contas/$id'
      preLoaderRoute: typeof AdminContasIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnunciosRoute: typeof AdminAnunciosRoute
  AdminAtendimentosRoute: typeof AdminAtendimentosRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminCatalogosRoute: typeof AdminCatalogosRoute
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminFooterRoute: typeof AdminFooterRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminSolicitacoesRoute: typeof AdminSolicitacoesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminContasIdRoute: typeof AdminContasIdRoute
  AdminContasIndexRoute: typeof AdminContasIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnunciosRoute: AdminAnunciosRoute,
  AdminAtendimentosRoute: AdminAtendimentosRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminCatalogosRoute: AdminCatalogosRoute,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminFooterRoute: AdminFooterRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminSolicitacoesRoute: AdminSolicitacoesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminContasIdRoute: AdminContasIdRoute,
  AdminContasIndexRoute: AdminContasIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CatalogosRouteChildren {
  CatalogosSlugRoute: typeof CatalogosSlugRoute
  CatalogosIndexRoute: typeof CatalogosIndexRoute
}

const CatalogosRouteChildren: CatalogosRouteChildren = {
  CatalogosSlugRoute: CatalogosSlugRoute,
  CatalogosIndexRoute: CatalogosIndexRoute,
}

const CatalogosRouteWithChildren = CatalogosRoute._addFileChildren(
  CatalogosRouteChildren,
)

interface ProdutosRouteChildren {
  ProdutosSlugRoute: typeof ProdutosSlugRoute
  ProdutosIndexRoute: typeof ProdutosIndexRoute
}

const ProdutosRouteChildren: ProdutosRouteChildren = {
  ProdutosSlugRoute: ProdutosSlugRoute,
  ProdutosIndexRoute: ProdutosIndexRoute,
}

const ProdutosRouteWithChildren = ProdutosRoute._addFileChildren(
  ProdutosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CatalogosRoute: CatalogosRouteWithChildren,
  ContatoRoute: ContatoRoute,
  DashboardRoute: DashboardRoute,
  MinhaContaRoute: MinhaContaRoute,
  ProdutosRoute: ProdutosRouteWithChildren,
  SobreRoute: SobreRoute,
  PaginasSlugRoute: PaginasSlugRoute,
  ApiPublicInitAdminRoute: ApiPublicInitAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
